2025-02-28 16:25:16 - fatura_bot - INFO - Encontrados 7 e-mails não lidos
2025-02-28 16:25:16 - fatura_bot - INFO - Encontrados 7 e-mails não lidos
2025-02-28 16:25:16 - fatura_bot - INFO - Encontrados 7 e-mails não lidos
2025-02-28 16:25:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2394&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2394&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2394&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:25 - fatura_bot - INFO - Arquivo salvo como: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:25:25 - fatura_bot - INFO - Arquivo salvo como: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:25:25 - fatura_bot - INFO - Arquivo salvo como: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:25:31 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:31 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:31 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:33 - fatura_bot - INFO - Arquivo salvo como: boleto - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:33 - fatura_bot - INFO - Arquivo salvo como: boleto - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:33 - fatura_bot - INFO - Arquivo salvo como: boleto - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:33 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:33 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:33 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:34 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:34 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:34 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:25:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:39 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:39 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:39 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:39 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:25:39 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:25:39 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2392&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:25:41 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:41 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:41 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - buquera transportes ltda - rctr-c - janeiro - 2025.xls
2025-02-28 16:25:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:25:47 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:47 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:47 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:25:49 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:25:49 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:25:49 - fatura_bot - INFO - Arquivo salvo como: boleto - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:25:49 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:49 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:49 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:25:54 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:54 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:54 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:25:54 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:25:54 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:25:54 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:26:02 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:02 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:02 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:02 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:26:02 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:26:02 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:26:11 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:11 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:11 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:26:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:26:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:26:16 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:16 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:16 - fatura_bot - INFO - Arquivo salvo como: relação embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:16 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=8
2025-02-28 16:26:16 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=8
2025-02-28 16:26:16 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=8
2025-02-28 16:26:23 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:23 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:23 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:23 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=9
2025-02-28 16:26:23 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=9
2025-02-28 16:26:23 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2393&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=9
2025-02-28 16:26:28 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:28 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:28 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:34 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:36 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:36 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:36 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:26:36 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:36 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:36 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2390&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:38 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:38 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:38 - fatura_bot - INFO - Arquivo salvo como: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:26:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:46 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:26:47 - fatura_bot - INFO - Arquivo salvo como: boleto - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:26:47 - fatura_bot - INFO - Arquivo salvo como: boleto - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:26:47 - fatura_bot - INFO - Arquivo salvo como: boleto - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:26:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:47 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2391&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:26:53 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:26:53 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:26:53 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:27:00 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:00 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:00 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:03 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:03 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:03 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:03 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:03 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:03 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:04 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:04 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:04 - fatura_bot - INFO - Arquivo salvo como: boleto - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:04 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:04 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:04 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:07 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:07 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:07 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:07 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:27:07 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:27:07 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=5
2025-02-28 16:27:11 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:11 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:11 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:27:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:27:11 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=6
2025-02-28 16:27:12 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:12 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:12 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:27:12 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:27:12 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:27:12 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2388&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=7
2025-02-28 16:27:13 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:13 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:13 - fatura_bot - INFO - Arquivo salvo como: resumo de embarques - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:27:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:19 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=2
2025-02-28 16:27:20 - fatura_bot - INFO - Arquivo salvo como: boleto - organizacoes fergon ltda - rctr-c - novembro - 2024.pdf
2025-02-28 16:27:20 - fatura_bot - INFO - Arquivo salvo como: boleto - organizacoes fergon ltda - rctr-c - novembro - 2024.pdf
2025-02-28 16:27:20 - fatura_bot - INFO - Arquivo salvo como: boleto - organizacoes fergon ltda - rctr-c - novembro - 2024.pdf
2025-02-28 16:27:20 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:20 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:20 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=3
2025-02-28 16:27:22 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:27:22 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:27:22 - fatura_bot - INFO - Arquivo salvo como: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:27:22 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:22 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:22 - fatura_bot - INFO - Baixando anexo: https://lrvseguros.com.br:2096/cpsess1481924706/3rdparty/roundcube/?_task=mail&_action=get&_mbox=INBOX&_uid=2389&_token=T3WcCqiu3WU6EumiZyJ8R094riNFUlVO&_part=4
2025-02-28 16:27:24 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - organizacoes fergon ltda - rctr-c - novembro - 2024.xlsx
2025-02-28 16:27:24 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - organizacoes fergon ltda - rctr-c - novembro - 2024.xlsx
2025-02-28 16:27:24 - fatura_bot - INFO - Arquivo salvo como: relação de embarques - organizacoes fergon ltda - rctr-c - novembro - 2024.xlsx
2025-02-28 16:27:28 - fatura_bot - INFO - E-mails arquivados com sucesso
2025-02-28 16:27:28 - fatura_bot - INFO - E-mails arquivados com sucesso
2025-02-28 16:27:28 - fatura_bot - INFO - E-mails arquivados com sucesso
2025-02-28 16:27:30 - fatura_bot - INFO - Processando documento: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:27:30 - fatura_bot - INFO - Processando documento: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:27:30 - fatura_bot - INFO - Processando documento: fatura e boleto - breve express transportes eireli - rctr-c - novembro - 2024.pdf
2025-02-28 16:28:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:28:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:28:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:30:21 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:30:21 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:30:21 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:30:23 - fatura_bot - ERROR - Erro ao processar documento Sura: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 122, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sura'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:30:23 - fatura_bot - ERROR - Erro ao processar documento Sura: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 122, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sura'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:30:23 - fatura_bot - ERROR - Erro ao processar documento Sura: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 122, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sura'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:30:23 - fatura_bot - INFO - Processando documento: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:30:23 - fatura_bot - INFO - Processando documento: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:30:23 - fatura_bot - INFO - Processando documento: endosso de fatura - buquera transportes ltda - rctr-c - janeiro - 2025.pdf
2025-02-28 16:30:48 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:30:48 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:30:48 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:33:41 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:33:41 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:33:41 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:33:43 - fatura_bot - ERROR - Erro ao processar documento AIG: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 166, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['aig'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:33:43 - fatura_bot - ERROR - Erro ao processar documento AIG: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 166, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['aig'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:33:43 - fatura_bot - ERROR - Erro ao processar documento AIG: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 166, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['aig'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:33:43 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:33:43 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:33:43 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:34:08 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:34:08 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:34:08 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:37:02 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:37:02 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:37:02 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:37:04 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:37:04 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:37:04 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:37:04 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:37:04 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:37:04 - fatura_bot - INFO - Processando documento: endosso de fatura - glenio da silva morais me - rctr-c - dezembro - 2024.pdf
2025-02-28 16:37:27 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:37:27 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:37:27 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:39:45 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 373, in quiver
    botao_voltar.click()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:39:45 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 373, in quiver
    botao_voltar.click()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:39:45 - fatura_bot - ERROR - Erro ao processar documento Fairfax: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 109, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['fairfax'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 373, in quiver
    botao_voltar.click()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <iframe id="ScanImagem" name="ScanImagem" height="207" width="100%" scrolling="Auto" src="FrmUploadImagens.aspx?ScanImagem_Cliente=3045&amp;ScanImagem_Orcamento=0&amp;ScanImagem_Divisao=0&amp;ScanImagem_Lancamento=&amp;ScanImagem_Sinistro=0&amp;ScanImagem_Documento=28547&amp;ScanImagem_Alteracao=31565&amp;ScanImagem_Contrato=0&amp;ScanImagem_ApolColetiva=0&amp;paginaOrigem=Documento&amp;pagina=ScanImagem&amp;ScanImagem_Recibo=0&amp;ScanImagem_TipoInformacao=2&amp;IDSESSAO=c0M3RE5aZ1ZCQURVVTI4S2lVRTAxdUNpNU5nN2gzMDFpdFJ2cmJ4T0RBOEhCY2xHWFJHbHJ1MGFlek52Ny8zUg==&amp;IDSESSAOABA=105170900&amp;TipoJanela=S" frameborder="0" runat="server" cd_frame_id_="5f0868335c6ffb2697b2b16de44988ea"></iframe> is not clickable at point (202, 304). Other element would receive the click: <div class="efeitoOverlay">...</div>
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECC071E9]
	(No symbol) [0x00007FF6ECC04BA2]
	(No symbol) [0x00007FF6ECC023CF]
	(No symbol) [0x00007FF6ECC00B51]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:39:45 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:39:45 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:39:45 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:40:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:40:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:40:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:40:58 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:40:58 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:40:58 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"body"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:40:58 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:40:58 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:40:58 - fatura_bot - INFO - Processando documento: resumo, relação de embarques e boleto - livia de castro transportes ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:41:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:41:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:41:19 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:43:11 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:43:11 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:43:11 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:43:13 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:43:13 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:43:13 - fatura_bot - ERROR - Erro ao processar documento Sompo: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 135, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['sompo'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:43:13 - fatura_bot - INFO - Processando documento: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:43:13 - fatura_bot - INFO - Processando documento: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:43:13 - fatura_bot - INFO - Processando documento: resumo de embarques - midas comercio importacao e distribuicao ltda - nacional - dezembro - 2024.pdf
2025-02-28 16:43:33 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:43:33 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:43:33 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:45:43 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:45:43 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:45:43 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:45:46 - fatura_bot - ERROR - Erro ao processar documento Berkley: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 179, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['berkley'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:45:46 - fatura_bot - ERROR - Erro ao processar documento Berkley: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 179, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['berkley'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:45:46 - fatura_bot - ERROR - Erro ao processar documento Berkley: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 179, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['berkley'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:45:46 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:45:46 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:45:46 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rcf-dc - dezembro - 2024.pdf
2025-02-28 16:46:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:46:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:46:04 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:48:31 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:48:31 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:48:31 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:48:33 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:48:33 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:48:33 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:48:33 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:48:33 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:48:33 - fatura_bot - INFO - Processando documento: endosso de fatura - next logistica ltda - rctr-c - dezembro - 2024.pdf
2025-02-28 16:48:53 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:48:53 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:48:53 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:51:20 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:51:20 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:51:20 - fatura_bot - INFO - Botão voltar #1 acionado
2025-02-28 16:51:22 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:51:22 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:51:22 - fatura_bot - ERROR - Erro ao processar documento AXA: Message: ScanImagem
Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ScanImagem"]"}
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBFF346]
	(No symbol) [0x00007FF6ECBFF57C]
	(No symbol) [0x00007FF6ECC52B17]
	(No symbol) [0x00007FF6ECC2736F]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 153, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['axa'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 393, in quiver
    driver.switch_to.frame("ScanImagem")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: ScanImagem

2025-02-28 16:51:22 - fatura_bot - INFO - Processando documento: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:51:22 - fatura_bot - INFO - Processando documento: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:51:22 - fatura_bot - INFO - Processando documento: endosso de fatura - organizacoes fergon ltda - rctr-c -novembro - 2024.pdf
2025-02-28 16:51:42 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:51:42 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:51:42 - fatura_bot - INFO - Iniciando processo de automação
2025-02-28 16:52:37 - fatura_bot - ERROR - Erro ao processar documento Swiss: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 96, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['swiss'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 301, in send_keys
    self._execute(
    ~~~~~~~~~~~~~^
        Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:52:37 - fatura_bot - ERROR - Erro ao processar documento Swiss: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 96, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['swiss'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 301, in send_keys
    self._execute(
    ~~~~~~~~~~~~~^
        Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:52:37 - fatura_bot - ERROR - Erro ao processar documento Swiss: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]
Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 260, in quiver
    campo_meio_pag.click()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 119, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8DCC]
	(No symbol) [0x00007FF6ECC00774]
	(No symbol) [0x00007FF6ECBF2314]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\cadastro_fatura2.py", line 96, in <module>
    quiver(dados, documento, tipo_seguradora=TIPO_SEGURADORA['swiss'])
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ESTAGIARIO\Desktop\bots\Bot-Faturas\src\services\web_automation.py", line 299, in quiver
    driver.find_element(By.TAG_NAME, "body").send_keys(Keys.ENTER)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 301, in send_keys
    self._execute(
    ~~~~~~~~~~~~~^
        Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webelement.py", line 570, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ESTAGIARIO\AppData\Roaming\Python\Python313\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=133.0.6943.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDAC6A5+28789]
	(No symbol) [0x00007FF6ECD15B20]
	(No symbol) [0x00007FF6ECBA8F9A]
	(No symbol) [0x00007FF6ECBBEDA4]
	(No symbol) [0x00007FF6ECBBD873]
	(No symbol) [0x00007FF6ECBB16D1]
	(No symbol) [0x00007FF6ECBAF402]
	(No symbol) [0x00007FF6ECBB376C]
	(No symbol) [0x00007FF6ECBB383F]
	(No symbol) [0x00007FF6ECC001AA]
	(No symbol) [0x00007FF6ECBF5D0B]
	(No symbol) [0x00007FF6ECC2732A]
	(No symbol) [0x00007FF6ECBF1BC6]
	(No symbol) [0x00007FF6ECC27540]
	(No symbol) [0x00007FF6ECC4F7E3]
	(No symbol) [0x00007FF6ECC27103]
	(No symbol) [0x00007FF6ECBEFFC0]
	(No symbol) [0x00007FF6ECBF1273]
	GetHandleVerifier [0x00007FF6ED0F1AED+3458237]
	GetHandleVerifier [0x00007FF6ED10829C+3550316]
	GetHandleVerifier [0x00007FF6ED0FDB9D+3507565]
	GetHandleVerifier [0x00007FF6ECE72C6A+841274]
	(No symbol) [0x00007FF6ECD209EF]
	(No symbol) [0x00007FF6ECD1CB34]
	(No symbol) [0x00007FF6ECD1CCD6]
	(No symbol) [0x00007FF6ECD0C119]
	BaseThreadInitThunk [0x00007FFCE356259D+29]
	RtlUserThreadStart [0x00007FFCE3B0AF38+40]

2025-02-28 16:52:37 - fatura_bot - INFO - Processamento concluído
2025-02-28 16:52:37 - fatura_bot - INFO - Processamento concluído
2025-02-28 16:52:37 - fatura_bot - INFO - Processamento concluído
